<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:TalendMetadata="http://www.talend.org/metadata/connection/2010" xmlns:orgomg.cwm.resource.relational="http:///orgomg/cwm/resource/relational.ecore">
  <TalendMetadata:DatabaseConnection xmi:id="_1UffsD8kEeiqZrDSltNxvA" name="HiveVirtBox" id="_YZKaQD6fEeiqZrDSltNxvA" label="HiveVirtBox" dataPackage="_1UgGwD8kEeiqZrDSltNxvA" DatabaseType="Hive" DriverClass="org.apache.hadoop.hive.jdbc.HiveDriver" URL="jdbc:hive2://localhost:10000/default;com.mysql.jdbc.Driver" dbVersionString="STANDALONE" Port="10000" Username="maria_dev" Password="" ServerName="localhost" SID="default" SqlSynthax="SQL Syntax" DbmsId="hive_id" ProductId="HIVE" StandardSQL="true" UiSchema="default">
    <taggedValue xmi:id="_1UffsT8kEeiqZrDSltNxvA" tag="Is Conn Need Reload" value="true"/>
    <taggedValue xmi:id="_1Uffsj8kEeiqZrDSltNxvA" tag="package filter" value=""/>
    <taggedValue xmi:id="_1Uffsz8kEeiqZrDSltNxvA" tag="Status" value=""/>
    <taggedValue xmi:id="_1UfftD8kEeiqZrDSltNxvA" tag="Version" value="0.1"/>
    <taggedValue xmi:id="_1UfftT8kEeiqZrDSltNxvA" tag="Purpose" value=""/>
    <taggedValue xmi:id="_1Ufftj8kEeiqZrDSltNxvA" tag="Description" value=""/>
    <taggedValue xmi:id="_1Ufftz8kEeiqZrDSltNxvA" tag="Author" value=""/>
    <taggedValue xmi:id="_1UffuD8kEeiqZrDSltNxvA" tag="otherParameter"/>
    <taggedValue xmi:id="_1UffuT8kEeiqZrDSltNxvA" tag="DB ProductName" value="Apache Hive"/>
    <taggedValue xmi:id="_1Uffuj8kEeiqZrDSltNxvA" tag="DB ProductVersion" value="1.2.1000.2.6.4.0-91"/>
    <parameters xmi:id="_1Uffuz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_DB_PORT"/>
    <parameters xmi:id="_1UffvD8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USE_YARN" value="true"/>
    <parameters xmi:id="_1UffvT8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_RESOURCEMANAGER_SCHEDULER_ADDRESS" value="localhost:8030"/>
    <parameters xmi:id="_1Uffvj8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USE_CUSTOM_CONFS" value="false"/>
    <parameters xmi:id="_1Uffvz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_NAME_NODE_URL" value="hdfs://localhost:8020"/>
    <parameters xmi:id="_1UffwD8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USERNAME" value="maria_dev"/>
    <parameters xmi:id="_1UffwT8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HADOOP_CLUSTER_ID" value="_ONOSED6cEeiqZrDSltNxvA"/>
    <parameters xmi:id="_1Uffwj8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_JOB_HISTORY_PRINCIPAL" value="mapred/_HOST@EXAMPLE.COM"/>
    <parameters xmi:id="_1Uffwz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HBASE_VERSION" value="HDP_2_6"/>
    <parameters xmi:id="_1UffxD8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_JOB_TRACKER_URL" value="localhost:8032"/>
    <parameters xmi:id="_1UffxT8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_JOBHISTORY_ADDRESS" value="127.0.0.1:8080"/>
    <parameters xmi:id="_1Uffxj8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HIVE_VERSION" value="HDP_2_6"/>
    <parameters xmi:id="_1Uffxz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USE_DATANODE_HOSTNAME" value="false"/>
    <parameters xmi:id="_1UffyD8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_DB_SERVER" value="localhost"/>
    <parameters xmi:id="_1UffyT8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_DB_TYPE" value="Hive"/>
    <parameters xmi:id="_1Uffyj8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_MAPRDB_AUTHENTICATION_USE_MAPRTICKET" value="false"/>
    <parameters xmi:id="_1Uffyz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_JOB_TRACKER_PRINCIPAL" value="yarn/_HOST@EXAMPLE.COM"/>
    <parameters xmi:id="_1UffzD8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HIVE_DISTRIBUTION" value="HORTONWORKS"/>
    <parameters xmi:id="_1UffzT8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_MAPRDB_VERSION" value="HDP_2_6"/>
    <parameters xmi:id="_1Uffzj8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_MAPRDB_DISTRIBUTION" value="HORTONWORKS"/>
    <parameters xmi:id="_1Uffzz8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USE_KRB" value="false"/>
    <parameters xmi:id="_1Uff0D8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HBASE_DISTRIBUTION" value="HORTONWORKS"/>
    <parameters xmi:id="_1Uff0T8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_STAGING_DIRECTORY" value="/user"/>
    <parameters xmi:id="_1Uff0j8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HADOOP_CUSTOM_JARS"/>
    <parameters xmi:id="_1Uff0z8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_NAME_NODE_PRINCIPAL" value="nn/_HOST@EXAMPLE.COM"/>
    <parameters xmi:id="_1Uff1D8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_DB_PRODUCT" value="HIVE"/>
    <parameters xmi:id="_1Uff1T8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HIVE_AUTHENTICATION_USE_MAPRTICKET" value="false"/>
    <parameters xmi:id="_1Uff1j8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HBASE_AUTHENTICATION_USE_MAPRTICKET" value="false"/>
    <parameters xmi:id="_1Uff1z8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_MAPRDB_TABLE_NS_MAPPING" value=""/>
    <parameters xmi:id="_1Uff2D8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HIVE_MODE" value="STANDALONE"/>
    <parameters xmi:id="_1Uff2T8kEeiqZrDSltNxvA" key="HIVE_SERVER_VERSION" value="HIVE2"/>
    <parameters xmi:id="_1Uff2j8kEeiqZrDSltNxvA" key="HIVE_AUTHENTICATION_HIVEPRINCIPLA" value="hive/_HOST@EXAMPLE.COM"/>
    <parameters xmi:id="_1Uff2z8kEeiqZrDSltNxvA" key="HIVE_AUTHENTICATION_METASTOREURL" value=""/>
    <parameters xmi:id="_1Uff3D8kEeiqZrDSltNxvA" key="HIVE_AUTHENTICATION_DRIVERCLASS" value=""/>
    <parameters xmi:id="_1Uff3T8kEeiqZrDSltNxvA" key="HIVE_AUTHENTICATION_USERNAME" value=""/>
    <parameters xmi:id="_1Uff3j8kEeiqZrDSltNxvA" key="HIVE_AUTHENTICATION_PASSWORD" value=""/>
    <parameters xmi:id="_1Uff3z8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_KEYTAB_PRINCIPLA" value=""/>
    <parameters xmi:id="_1Uff4D8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_KEYTAB" value=""/>
    <parameters xmi:id="_1Uff4T8kEeiqZrDSltNxvA" key="HIVE_EXECUTION_ENGINE" value="tez"/>
    <parameters xmi:id="_1Uff4j8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_USE_SSL" value="false"/>
    <parameters xmi:id="_1Uff4z8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_SSL_TRUST_STORE_PATH" value=""/>
    <parameters xmi:id="_1Uff5D8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_SSL_TRUST_STORE_PASSWORD" value=""/>
    <parameters xmi:id="_1Uff5T8kEeiqZrDSltNxvA" key="CONN_PARA_KEY_HIVE_ADDITIONAL_JDBC_SETTINGS" value="com.mysql.jdbc.Driver"/>
  </TalendMetadata:DatabaseConnection>
  <orgomg.cwm.resource.relational:Schema xmi:id="_1UgGwD8kEeiqZrDSltNxvA" name="default" dataManager="_1UffsD8kEeiqZrDSltNxvA"/>
</xmi:XMI>
